version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: webpack
    versions:
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.0
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.26.0
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.8
  - dependency-name: "@babel/runtime"
    versions:
    - 7.13.6
    - 7.13.7
  - dependency-name: karma-webpack
    versions:
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  labels:
  - dependencies
