name: Test
on:
  push:
    branches:
    - '**'
jobs:
  test-php:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Install dependencies
      run: composer install --prefer-dist
    - name: Run tests
      run: composer run-script test

  test-js:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm install
    - name: Run Webpack build
      run: npm run build
    - name: Run tests
      run: npm run test-ci
